name: Windows with AnyDesk

on:
  workflow_dispatch:

jobs:
  run-windows:
    runs-on: windows-latest
    steps:
      - name: Instalar AnyDesk
        run: |
          choco install anydesk -y
          Start-Sleep -Seconds 30
      - name: Mostrar AnyDesk ID
        run: |
          $id = (Get-Content "$env:PROGRAMDATA\AnyDesk\ad.mad" | Select-String -Pattern "^[0-9]+$").Matches.Value
          Write-Output "AnyDesk ID: $id"
          Start-Sleep -Seconds 3600
