name: Windows with AnyDesk

on:
  workflow_dispatch:

jobs:
  run-windows:
    runs-on: windows-latest
    steps:
      - name: Instalar AnyDesk
        run: |
          choco install anydesk -y
          Start-Sleep -Seconds 30

      - name: Abrir AnyDesk y dejar la VM encendida
        run: |
          Write-Output "Abre AnyDesk desde el icono en el escritorio para ver tu ID."
          Start-Sleep -Seconds 3600
