name: Windows with AnyDesk

on:
  workflow_dispatch:

jobs:
  run-windows:
    runs-on: windows-latest
    steps:
      - name: Instalar AnyDesk
        run: |
          choco install anydesk -y
          Start-Sleep -Seconds 30

      - name: Mostrar AnyDesk ID y mantener la VM activa
        run: |
          Write-Output "Esperando 30 segundos para que AnyDesk arranque..."
          Start-Sleep -Seconds 30

          Write-Output "Proceso AnyDesk:"
          Get-Process | Where-Object { $_.ProcessName -like "*anydesk*" }

          Write-Output "Abre el ícono de AnyDesk en la VM para ver el ID en pantalla."
          Start-Sleep -Seconds 3600
