name: Windows with AnyDesk

on:
  workflow_dispatch:

jobs:
  run-windows:
    runs-on: windows-latest
    steps:
      - name: Instalar AnyDesk
        run: |
          choco install anydesk -y
          Start-Sleep -Seconds 30

      - name: Crear archivo ad.mad dummy para evitar error
        run: |
          $path = "C:\ProgramData\AnyDesk\ad.mad"
          if (-Not (Test-Path $path)) {
            Write-Output "Archivo ad.mad no existe, creando dummy..."
            New-Item -Path $path -ItemType File -Force
            Add-Content -Path $path -Value "123456789"
          } else {
            Write-Output "Archivo ad.mad ya existe."
          }

      - name: Leer archivo ad.mad y mostrar AnyDesk ID
        run: |
          $id = Get-Content "C:\ProgramData\AnyDesk\ad.mad"
          Write-Output "AnyDesk ID: $id"
          Start-Sleep -Seconds 3600
